<a href="https://colab.research.google.com/github/444112029012/phishing-detection-project/blob/main/colab/%E5%85%83%E6%A8%A1%E5%9E%8B%E5%BB%BA%E7%AB%8B/composite_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
from xgboost import XGBClassifier
xgb_url_model = XGBClassifier()
xgb_url_model.load_model('/content/optuna_xgb_url_final.json')

In [22]:
from xgboost import XGBClassifier
xgb_html_model = XGBClassifier()
xgb_html_model.load_model('/content/optuna_xgb_html_final.json')

In [23]:
from xgboost import XGBClassifier
xgb_ai_model = XGBClassifier()
xgb_ai_model.load_model('/content/optuna_xgb_ai_final.json')

In [24]:
import pandas as pd

In [25]:
df = pd.read_csv('/content/Dataset_Meta_Set.csv')

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54590 entries, 0 to 54589
Data columns (total 78 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   url                                54590 non-null  object
 1   target                             54590 non-null  int64
 2   length_url                         54590 non-null  int64
 3   length_hostname                    54590 non-null  int64
 4   ip                                 54590 non-null  int64
 5   nb_dots                            54590 non-null  int64
 6   nb_hyphens                         54590 non-null  int64
 7   nb_at                              54590 non-null  int64
 8   nb_qm                              54590 non-null  int64
 9   nb_and                             54590 non-null  int64
 10  nb_or                              54590 non-null  int64
 11  nb_eq                              54590 non-null  int64
 12  nb_underscore                      54590 non-null  int64
 13  nb_tilde                           54590 non-null  int64
 14  nb_percent                         54590 non-null  int64
 15  nb_slash                           54590 non-null  int64
 16  nb_star                            54590 non-null  int64
 17  nb_colon                           54590 non-null  int64
 18  nb_comma                           54590 non-null  int64
 19  nb_semicolumn                      54590 non-null  int64
 20  nb_dollar                          54590 non-null  int64
 21  nb_space                           54590 non-null  int64
 22  nb_www                             54590 non-null  int64
 23  nb_com                             54590 non-null  int64
 24  nb_dslash                          54590 non-null  int64
 25  http_in_path                       54590 non-null  int64
 26  https_token                        54590 non-null  int64
 27  ratio_digits_url                   54590 non-null  float64
 28  ratio_digits_host                  54590 non-null  float64
 29  punycode                           54590 non-null  int64
 30  port                               54590 non-null  int64
 31  tld_in_path                        54590 non-null  int64
 32  tld_in_subdomain                   54590 non-null  int64
 33  nb_subdomains                      54590 non-null  int64
 34  abnormal_subdomain                 54590 non-null  int64
 35  prefix_suffix                      54590 non-null  int64
 36  path_extension                     54590 non-null  int64
 37  length_words_raw                   54590 non-null  int64
 38  char_repeat                        54590 non-null  int64
 39  shortest_word_host                 54590 non-null  int64
 40  shortest_word_path                 54590 non-null  int64
 41  longest_words_raw                  54590 non-null  int64
 42  longest_word_host                  54590 non-null  int64
 43  longest_word_path                  54590 non-null  int64
 44  avg_words_raw                      54590 non-null  float64
 45  avg_word_host                      54590 non-null  float64
 46  avg_word_path                      54590 non-null  float64
 47  phish_hints                        54590 non-null  float64
 48  domain_in_brand                    54590 non-null  float64
 49  nb_hyperlinks                      54590 non-null  float64
 50  ratio_intHyperlinks                54590 non-null  float64
 51  ratio_extHyperlinks                54590 non-null  float64
 52  ratio_extRedirection               54590 non-null  float64
 53  ratio_extErrors                    54590 non-null  float64
 54  external_favicon                   54590 non-null  float64
 55  links_in_tags                      54590 non-null  float64
 56  ratio_extMedia                     54590 non-null  float64
 57  safe_anchor                        54590 non-null  float64
 58  empty_title                        54590 non-null  float64
 59  domain_in_title                    54590 non-null  float64
 60  domain_with_copyright              54590 non-null  float64
 61  has_meta_refresh                   54590 non-null  float64
 62  has_js_redirect                    54590 non-null  float64
 63  creates_urgency                    54590 non-null  bool
 64  uses_threats                       54590 non-null  bool
 65  requests_sensitive_info            54590 non-null  bool
 66  offers_unrealistic_rewards         54590 non-null  bool
 67  has_spelling_grammar_errors        54590 non-null  bool
 68  impersonated_brand                 15873 non-null  object
 69  has_valid_copyright_year           54590 non-null  bool
 70  is_content_login_focused           54590 non-null  bool
 71  has_rich_navigation                54590 non-null  bool
 72  has_physical_address               54590 non-null  bool
 73  has_phone_number                   54590 non-null  bool
 74  content_consistency_score          54590 non-null  float64
 75  language_professionalism_score     54590 non-null  float64
 76  overall_phishing_likelihood_score  54590 non-null  float64
 77  text_length                        54590 non-null  int64
dtypes: bool(10), float64(24), int64(42), object(2)
memory usage: 28.8+ MB

In [27]:
df_con = df.copy()
df_con

,url,target,length_url,length_hostname,ip,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,...,impersonated_brand,has_valid_copyright_year,is_content_login_focused,has_rich_navigation,has_physical_address,has_phone_number,content_consistency_score,language_professionalism_score,overall_phishing_likelihood_score,text_length
0,https://www.daftlogic.com,1,25,17,0,2,0,0,0,0,...,NaN,True,False,True,False,False,8.0,9.0,2.0,5906
1,https://www.ref.ac.uk,1,21,13,0,3,0,0,0,0,...,NaN,True,False,True,False,False,8.0,9.0,2.0,3943
2,https://www.action24.gr,1,23,15,0,2,0,0,0,0,...,ACTION 24,True,False,False,False,False,8.0,9.0,2.0,4164
3,https://www.mytennis.info,1,25,17,0,2,0,0,0,0,...,Tennis Mania GmbH,True,False,True,False,False,7.0,9.0,2.0,4438
4,https://inmaculada.edu.ec/,0,26,17,0,2,0,0,0,0,...,NaN,True,False,True,True,True,8.0,9.0,2.0,3298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54585,https://www.obsolete-tears.com,1,30,22,0,2,1,0,0,0,...,NaN,True,False,True,False,False,8.0,9.0,2.0,2971
54586,https://www.twilightersdream.com,1,32,24,0,2,0,0,0,0,...,NaN,False,False,False,False,False,7.0,9.0,2.0,15623
54587,https://www.dtu.dk,1,18,10,0,2,0,0,0,0,...,NaN,True,False,True,True,False,9.0,9.0,2.0,11320
54588,http://3.ly/uja,1,15,4,0,1,0,0,0,0,...,NaN,False,False,True,False,False,7.0,10.0,2.0,900
54589,https://www.maxillumination.com,1,31,23,0,2,0,0,0,0,...,NaN,False,False,True,True,True,7.0,9.0,2.0,2113

In [28]:
df_con.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54590 entries, 0 to 54589
Data columns (total 78 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   url                                54590 non-null  object
 1   target                             54590 non-null  int64
 2   length_url                         54590 non-null  int64
 3   length_hostname                    54590 non-null  int64
 4   ip                                 54590 non-null  int64
 5   nb_dots                            54590 non-null  int64
 6   nb_hyphens                         54590 non-null  int64
 7   nb_at                              54590 non-null  int64
 8   nb_qm                              54590 non-null  int64
 9   nb_and                             54590 non-null  int64
 10  nb_or                              54590 non-null  int64
 11  nb_eq                              54590 non-null  int64
 12  nb_underscore                      54590 non-null  int64
 13  nb_tilde                           54590 non-null  int64
 14  nb_percent                         54590 non-null  int64
 15  nb_slash                           54590 non-null  int64
 16  nb_star                            54590 non-null  int64
 17  nb_colon                           54590 non-null  int64
 18  nb_comma                           54590 non-null  int64
 19  nb_semicolumn                      54590 non-null  int64
 20  nb_dollar                          54590 non-null  int64
 21  nb_space                           54590 non-null  int64
 22  nb_www                             54590 non-null  int64
 23  nb_com                             54590 non-null  int64
 24  nb_dslash                          54590 non-null  int64
 25  http_in_path                       54590 non-null  int64
 26  https_token                        54590 non-null  int64
 27  ratio_digits_url                   54590 non-null  float64
 28  ratio_digits_host                  54590 non-null  float64
 29  punycode                           54590 non-null  int64
 30  port                               54590 non-null  int64
 31  tld_in_path                        54590 non-null  int64
 32  tld_in_subdomain                   54590 non-null  int64
 33  nb_subdomains                      54590 non-null  int64
 34  abnormal_subdomain                 54590 non-null  int64
 35  prefix_suffix                      54590 non-null  int64
 36  path_extension                     54590 non-null  int64
 37  length_words_raw                   54590 non-null  int64
 38  char_repeat                        54590 non-null  int64
 39  shortest_word_host                 54590 non-null  int64
 40  shortest_word_path                 54590 non-null  int64
 41  longest_words_raw                  54590 non-null  int64
 42  longest_word_host                  54590 non-null  int64
 43  longest_word_path                  54590 non-null  int64
 44  avg_words_raw                      54590 non-null  float64
 45  avg_word_host                      54590 non-null  float64
 46  avg_word_path                      54590 non-null  float64
 47  phish_hints                        54590 non-null  float64
 48  domain_in_brand                    54590 non-null  float64
 49  nb_hyperlinks                      54590 non-null  float64
 50  ratio_intHyperlinks                54590 non-null  float64
 51  ratio_extHyperlinks                54590 non-null  float64
 52  ratio_extRedirection               54590 non-null  float64
 53  ratio_extErrors                    54590 non-null  float64
 54  external_favicon                   54590 non-null  float64
 55  links_in_tags                      54590 non-null  float64
 56  ratio_extMedia                     54590 non-null  float64
 57  safe_anchor                        54590 non-null  float64
 58  empty_title                        54590 non-null  float64
 59  domain_in_title                    54590 non-null  float64
 60  domain_with_copyright              54590 non-null  float64
 61  has_meta_refresh                   54590 non-null  float64
 62  has_js_redirect                    54590 non-null  float64
 63  creates_urgency                    54590 non-null  bool
 64  uses_threats                       54590 non-null  bool
 65  requests_sensitive_info            54590 non-null  bool
 66  offers_unrealistic_rewards         54590 non-null  bool
 67  has_spelling_grammar_errors        54590 non-null  bool
 68  impersonated_brand                 15873 non-null  object
 69  has_valid_copyright_year           54590 non-null  bool
 70  is_content_login_focused           54590 non-null  bool
 71  has_rich_navigation                54590 non-null  bool
 72  has_physical_address               54590 non-null  bool
 73  has_phone_number                   54590 non-null  bool
 74  content_consistency_score          54590 non-null  float64
 75  language_professionalism_score     54590 non-null  float64
 76  overall_phishing_likelihood_score  54590 non-null  float64
 77  text_length                        54590 non-null  int64
dtypes: bool(10), float64(24), int64(42), object(2)
memory usage: 28.8+ MB

In [29]:
from sklearn.model_selection import train_test_split
X_url_test = df_con[['length_url', 'length_hostname', 'ip', 'nb_dots',
       'nb_hyphens', 'nb_at', 'nb_qm', 'nb_and', 'nb_or', 'nb_eq',
       'nb_underscore', 'nb_tilde', 'nb_percent', 'nb_slash', 'nb_star',
       'nb_colon', 'nb_comma', 'nb_semicolumn', 'nb_dollar', 'nb_space',
       'nb_www', 'nb_com', 'nb_dslash', 'http_in_path', 'https_token',
       'ratio_digits_url', 'ratio_digits_host', 'punycode', 'port',
       'tld_in_path', 'tld_in_subdomain', 'nb_subdomains',
       'abnormal_subdomain', 'prefix_suffix', 'path_extension',
       'length_words_raw', 'char_repeat', 'shortest_word_host',
       'shortest_word_path', 'longest_words_raw', 'longest_word_host',
       'longest_word_path', 'avg_words_raw', 'avg_word_host', 'avg_word_path'
    ]]
X_html_test = df_con[[
        'phish_hints', 'domain_in_brand', 'nb_hyperlinks', 'ratio_intHyperlinks',
        'ratio_extHyperlinks', 'ratio_extRedirection', 'ratio_extErrors',
        'external_favicon', 'links_in_tags', 'ratio_extMedia', 'safe_anchor',
        'empty_title', 'domain_in_title', 'domain_with_copyright',
        'has_meta_refresh', 'has_js_redirect'
        ]]
X_ai_test = df_con[['creates_urgency', 'uses_threats', 'requests_sensitive_info',
            'offers_unrealistic_rewards', 'has_spelling_grammar_errors',
            'impersonated_brand', 'has_valid_copyright_year',
            'is_content_login_focused', 'has_rich_navigation',
            'has_physical_address', 'has_phone_number',
            'content_consistency_score', 'language_professionalism_score',
            'overall_phishing_likelihood_score', 'text_length'
            ]]
y = df_con[['target']]

In [30]:
bool_col = ['creates_urgency', 'uses_threats', 'requests_sensitive_info',
            'offers_unrealistic_rewards', 'has_spelling_grammar_errors',
            'has_valid_copyright_year', 'is_content_login_focused',
            'has_rich_navigation', 'has_physical_address', 'has_phone_number']
X_ai_test[bool_col] = X_ai_test[bool_col].astype(int)
X_ai_test['impersonated_brand'] = [1 if k else 0 for k in X_ai_test['impersonated_brand'].notnull()]

/tmp/ipykernel_11148/1533107422.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_ai_test[bool_col] = X_ai_test[bool_col].astype(int)
/tmp/ipykernel_11148/1533107422.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_ai_test['impersonated_brand'] = [1 if k else 0 for k in X_ai_test['impersonated_brand'].notnull()]

In [31]:
X_ai_test

,creates_urgency,uses_threats,requests_sensitive_info,offers_unrealistic_rewards,has_spelling_grammar_errors,impersonated_brand,has_valid_copyright_year,is_content_login_focused,has_rich_navigation,has_physical_address,has_phone_number,content_consistency_score,language_professionalism_score,overall_phishing_likelihood_score,text_length
0,0,0,0,0,0,0,1,0,1,0,0,8.0,9.0,2.0,5906
1,0,0,0,0,0,0,1,0,1,0,0,8.0,9.0,2.0,3943
2,0,0,0,0,0,1,1,0,0,0,0,8.0,9.0,2.0,4164
3,0,0,0,0,0,1,1,0,1,0,0,7.0,9.0,2.0,4438
4,0,0,0,0,0,0,1,0,1,1,1,8.0,9.0,2.0,3298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54585,0,0,0,0,0,0,1,0,1,0,0,8.0,9.0,2.0,2971
54586,0,0,0,0,0,0,0,0,0,0,0,7.0,9.0,2.0,15623
54587,0,0,0,0,0,0,1,0,1,1,0,9.0,9.0,2.0,11320
54588,0,0,0,0,0,0,0,0,1,0,0,7.0,10.0,2.0,900
54589,0,0,0,0,0,0,0,0,1,1,1,7.0,9.0,2.0,2113

In [33]:
y_pred_proba_url = xgb_url_model.predict_proba(X_url_test)[:, 1]
y_pred_proba_html = xgb_html_model.predict_proba(X_html_test)[:, 1]
y_pred_proba_ai = xgb_ai_model.predict_proba(X_ai_test)[:, 1]

print('url', len(y_pred_proba_url))
print('html', len(y_pred_proba_html))
print('ai',len(y_pred_proba_ai))

url 54590
html 54590
ai 54590

In [34]:
print('url', y_pred_proba_url)
print('html', y_pred_proba_html)
print('ai',y_pred_proba_ai)

url [0.9975883  0.9984584  0.9932748  ... 0.99669063 0.91914546 0.99606836]
html [0.6424801  0.7061767  0.8890878  ... 0.19599754 0.3462597  0.9142355 ]
ai [0.7573119  0.70696515 0.573738   ... 0.81182015 0.68280536 0.64918846]

In [35]:
import numpy as np

In [36]:
X_meta = np.c_[y_pred_proba_url, y_pred_proba_html, y_pred_proba_ai]
y_meta = y

In [37]:
X_train_meta, X_test_meta, y_train_meta, y_test_meta = train_test_split(
    X_meta,
    y_meta,
    test_size=0.3,
    random_state=42,
    stratify=y_meta
)

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [41]:
len(y_train_meta[y_train_meta['target'] == 1])

33671

In [42]:
meta_model = LogisticRegression(class_weight='balanced')
meta_model.fit(X_train_meta, y_train_meta)

# 5. 評估元模型
final_score = meta_model.score(X_test_meta, y_test_meta)
print(f"最終堆疊模型的準確率: {final_score}")

最終堆疊模型的準確率: 0.9945655492458936

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, log_loss

# 1. 取得 "最終測試集" (X_test_meta, y_test_meta) 上的預測
y_pred = meta_model.predict(X_test_meta)
y_proba = meta_model.predict_proba(X_test_meta)[:, 1] # 取得機率

# 2. (必看) 混淆矩陣
print("--- 混淆矩陣 ---")
cm = confusion_matrix(y_test_meta, y_pred)
print(cm)
# [[TN, FP],
#  [FN, TP]]

# 3. (必看) 分類報告 (包含 Precision, Recall, F1)
print("\n--- 分類報告 ---")
report = classification_report(y_test_meta, y_pred, target_names=['安全 (0)', '釣魚 (1)'])
print(report)

# 4. (必看) ROC AUC
auc_score = roc_auc_score(y_test_meta, y_proba)
print(f"\nROC AUC 分數: {auc_score:.4f}")

# 5. (可選) Log Loss
log_loss_score = log_loss(y_test_meta, y_proba)
print(f"Log Loss 分數: {log_loss_score:.4f}")

--- 混淆矩陣 ---
[[1005    8]
 [   0 8799]]

--- 分類報告 ---
              precision    recall  f1-score   support

      安全 (0)       1.00      0.99      1.00      1013
      釣魚 (1)       1.00      1.00      1.00      8799

    accuracy                           1.00      9812
   macro avg       1.00      1.00      1.00      9812
weighted avg       1.00      1.00      1.00      9812


ROC AUC 分數: 0.9982
Log Loss 分數: 0.0128

In [ ]:
%%capture
!pip install joblib

In [43]:
import joblib
joblib.dump(meta_model, 'meta_logistic_final.pkl')

['meta_logistic_final.pkl']