<a href="https://colab.research.google.com/github/444112029012/phishing-detection-project/blob/main/colab/%E5%85%83%E6%A8%A1%E5%9E%8B%E5%BB%BA%E7%AB%8B/composite_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from xgboost import XGBClassifier
xgb_url_model = XGBClassifier()
xgb_url_model.load_model('/content/optuna_xgb_url_final.json')

In [3]:
from xgboost import XGBClassifier
xgb_html_model = XGBClassifier()
xgb_html_model.load_model('/content/optuna_xgb_html_final.json')

In [4]:
from xgboost import XGBClassifier
xgb_ai_model = XGBClassifier()
xgb_ai_model.load_model('/content/optuna_xgb_ai_final.json')

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('/content/Dataset_Meta_Set.csv')

In [9]:
from sklearn.model_selection import train_test_split
df_meta_train, df_meta_test = train_test_split(
    df,
    test_size=0.2,
    stratify=df['target'],
    random_state=42
)
df_meta_test.to_csv('meta_test.csv', index=False)

In [12]:
df_meta_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43672 entries, 41613 to 13543
Data columns (total 78 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   url                                43672 non-null  object
 1   target                             43672 non-null  int64
 2   length_url                         43672 non-null  int64
 3   length_hostname                    43672 non-null  int64
 4   ip                                 43672 non-null  int64
 5   nb_dots                            43672 non-null  int64
 6   nb_hyphens                         43672 non-null  int64
 7   nb_at                              43672 non-null  int64
 8   nb_qm                              43672 non-null  int64
 9   nb_and                             43672 non-null  int64
 10  nb_or                              43672 non-null  int64
 11  nb_eq                              43672 non-null  int64
 12  nb_underscore                      43672 non-null  int64
 13  nb_tilde                           43672 non-null  int64
 14  nb_percent                         43672 non-null  int64
 15  nb_slash                           43672 non-null  int64
 16  nb_star                            43672 non-null  int64
 17  nb_colon                           43672 non-null  int64
 18  nb_comma                           43672 non-null  int64
 19  nb_semicolumn                      43672 non-null  int64
 20  nb_dollar                          43672 non-null  int64
 21  nb_space                           43672 non-null  int64
 22  nb_www                             43672 non-null  int64
 23  nb_com                             43672 non-null  int64
 24  nb_dslash                          43672 non-null  int64
 25  http_in_path                       43672 non-null  int64
 26  https_token                        43672 non-null  int64
 27  ratio_digits_url                   43672 non-null  float64
 28  ratio_digits_host                  43672 non-null  float64
 29  punycode                           43672 non-null  int64
 30  port                               43672 non-null  int64
 31  tld_in_path                        43672 non-null  int64
 32  tld_in_subdomain                   43672 non-null  int64
 33  nb_subdomains                      43672 non-null  int64
 34  abnormal_subdomain                 43672 non-null  int64
 35  prefix_suffix                      43672 non-null  int64
 36  path_extension                     43672 non-null  int64
 37  length_words_raw                   43672 non-null  int64
 38  char_repeat                        43672 non-null  int64
 39  shortest_word_host                 43672 non-null  int64
 40  shortest_word_path                 43672 non-null  int64
 41  longest_words_raw                  43672 non-null  int64
 42  longest_word_host                  43672 non-null  int64
 43  longest_word_path                  43672 non-null  int64
 44  avg_words_raw                      43672 non-null  float64
 45  avg_word_host                      43672 non-null  float64
 46  avg_word_path                      43672 non-null  float64
 47  phish_hints                        43672 non-null  float64
 48  domain_in_brand                    43672 non-null  float64
 49  nb_hyperlinks                      43672 non-null  float64
 50  ratio_intHyperlinks                43672 non-null  float64
 51  ratio_extHyperlinks                43672 non-null  float64
 52  ratio_extRedirection               43672 non-null  float64
 53  ratio_extErrors                    43672 non-null  float64
 54  external_favicon                   43672 non-null  float64
 55  links_in_tags                      43672 non-null  float64
 56  ratio_extMedia                     43672 non-null  float64
 57  safe_anchor                        43672 non-null  float64
 58  empty_title                        43672 non-null  float64
 59  domain_in_title                    43672 non-null  float64
 60  domain_with_copyright              43672 non-null  float64
 61  has_meta_refresh                   43672 non-null  float64
 62  has_js_redirect                    43672 non-null  float64
 63  creates_urgency                    43672 non-null  bool
 64  uses_threats                       43672 non-null  bool
 65  requests_sensitive_info            43672 non-null  bool
 66  offers_unrealistic_rewards         43672 non-null  bool
 67  has_spelling_grammar_errors        43672 non-null  bool
 68  impersonated_brand                 12671 non-null  object
 69  has_valid_copyright_year           43672 non-null  bool
 70  is_content_login_focused           43672 non-null  bool
 71  has_rich_navigation                43672 non-null  bool
 72  has_physical_address               43672 non-null  bool
 73  has_phone_number                   43672 non-null  bool
 74  content_consistency_score          43672 non-null  float64
 75  language_professionalism_score     43672 non-null  float64
 76  overall_phishing_likelihood_score  43672 non-null  float64
 77  text_length                        43672 non-null  int64
dtypes: bool(10), float64(24), int64(42), object(2)
memory usage: 23.4+ MB

In [13]:
df_con = df_meta_train.copy()
df_con

,url,target,length_url,length_hostname,ip,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,...,impersonated_brand,has_valid_copyright_year,is_content_login_focused,has_rich_navigation,has_physical_address,has_phone_number,content_consistency_score,language_professionalism_score,overall_phishing_likelihood_score,text_length
41613,https://www.vmi.edu,1,19,11,0,2,0,0,0,0,...,NaN,True,False,True,True,True,10.0,10.0,2.0,5543
33558,http://969695665453012023.rf.gd/,0,32,24,0,2,0,0,0,0,...,NaN,False,False,False,False,False,7.0,10.0,2.0,2838
42697,https://www.passaporta.be,1,25,17,0,2,0,0,0,0,...,NaN,True,False,True,False,False,8.0,9.0,2.0,5332
41343,https://www.tvproapp.de,1,23,15,0,2,0,0,0,0,...,TV Pro,True,False,True,False,False,8.0,9.0,2.0,8211
12741,https://www.churchangel.com,1,27,19,0,2,0,0,0,0,...,NaN,True,True,True,False,False,8.0,10.0,6.0,3740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38594,https://www.sanfordherald.com,1,29,21,0,2,0,0,0,0,...,NaN,True,False,True,True,True,10.0,10.0,0.0,8113
1010,https://www.lovelyrings.de,1,26,18,0,2,0,0,0,0,...,NaN,True,False,True,False,True,8.0,9.0,2.0,10244
34569,https://www.wlac.edu,1,20,12,0,2,0,0,0,0,...,NaN,False,False,True,False,False,7.0,9.0,2.0,4470
9500,https://www.friendsjournal.org,1,30,22,0,2,0,0,0,0,...,NaN,True,False,True,False,False,7.0,9.0,3.0,4039
13543,https://www.cartier.com.br,1,26,18,0,3,0,0,0,0,...,Cartier,True,False,True,True,True,9.0,10.0,2.0,5819

In [14]:
df_con.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43672 entries, 41613 to 13543
Data columns (total 78 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   url                                43672 non-null  object
 1   target                             43672 non-null  int64
 2   length_url                         43672 non-null  int64
 3   length_hostname                    43672 non-null  int64
 4   ip                                 43672 non-null  int64
 5   nb_dots                            43672 non-null  int64
 6   nb_hyphens                         43672 non-null  int64
 7   nb_at                              43672 non-null  int64
 8   nb_qm                              43672 non-null  int64
 9   nb_and                             43672 non-null  int64
 10  nb_or                              43672 non-null  int64
 11  nb_eq                              43672 non-null  int64
 12  nb_underscore                      43672 non-null  int64
 13  nb_tilde                           43672 non-null  int64
 14  nb_percent                         43672 non-null  int64
 15  nb_slash                           43672 non-null  int64
 16  nb_star                            43672 non-null  int64
 17  nb_colon                           43672 non-null  int64
 18  nb_comma                           43672 non-null  int64
 19  nb_semicolumn                      43672 non-null  int64
 20  nb_dollar                          43672 non-null  int64
 21  nb_space                           43672 non-null  int64
 22  nb_www                             43672 non-null  int64
 23  nb_com                             43672 non-null  int64
 24  nb_dslash                          43672 non-null  int64
 25  http_in_path                       43672 non-null  int64
 26  https_token                        43672 non-null  int64
 27  ratio_digits_url                   43672 non-null  float64
 28  ratio_digits_host                  43672 non-null  float64
 29  punycode                           43672 non-null  int64
 30  port                               43672 non-null  int64
 31  tld_in_path                        43672 non-null  int64
 32  tld_in_subdomain                   43672 non-null  int64
 33  nb_subdomains                      43672 non-null  int64
 34  abnormal_subdomain                 43672 non-null  int64
 35  prefix_suffix                      43672 non-null  int64
 36  path_extension                     43672 non-null  int64
 37  length_words_raw                   43672 non-null  int64
 38  char_repeat                        43672 non-null  int64
 39  shortest_word_host                 43672 non-null  int64
 40  shortest_word_path                 43672 non-null  int64
 41  longest_words_raw                  43672 non-null  int64
 42  longest_word_host                  43672 non-null  int64
 43  longest_word_path                  43672 non-null  int64
 44  avg_words_raw                      43672 non-null  float64
 45  avg_word_host                      43672 non-null  float64
 46  avg_word_path                      43672 non-null  float64
 47  phish_hints                        43672 non-null  float64
 48  domain_in_brand                    43672 non-null  float64
 49  nb_hyperlinks                      43672 non-null  float64
 50  ratio_intHyperlinks                43672 non-null  float64
 51  ratio_extHyperlinks                43672 non-null  float64
 52  ratio_extRedirection               43672 non-null  float64
 53  ratio_extErrors                    43672 non-null  float64
 54  external_favicon                   43672 non-null  float64
 55  links_in_tags                      43672 non-null  float64
 56  ratio_extMedia                     43672 non-null  float64
 57  safe_anchor                        43672 non-null  float64
 58  empty_title                        43672 non-null  float64
 59  domain_in_title                    43672 non-null  float64
 60  domain_with_copyright              43672 non-null  float64
 61  has_meta_refresh                   43672 non-null  float64
 62  has_js_redirect                    43672 non-null  float64
 63  creates_urgency                    43672 non-null  bool
 64  uses_threats                       43672 non-null  bool
 65  requests_sensitive_info            43672 non-null  bool
 66  offers_unrealistic_rewards         43672 non-null  bool
 67  has_spelling_grammar_errors        43672 non-null  bool
 68  impersonated_brand                 12671 non-null  object
 69  has_valid_copyright_year           43672 non-null  bool
 70  is_content_login_focused           43672 non-null  bool
 71  has_rich_navigation                43672 non-null  bool
 72  has_physical_address               43672 non-null  bool
 73  has_phone_number                   43672 non-null  bool
 74  content_consistency_score          43672 non-null  float64
 75  language_professionalism_score     43672 non-null  float64
 76  overall_phishing_likelihood_score  43672 non-null  float64
 77  text_length                        43672 non-null  int64
dtypes: bool(10), float64(24), int64(42), object(2)
memory usage: 23.4+ MB

In [15]:
from sklearn.model_selection import train_test_split
X_url_test = df_con[['length_url', 'length_hostname', 'ip', 'nb_dots',
       'nb_hyphens', 'nb_at', 'nb_qm', 'nb_and', 'nb_or', 'nb_eq',
       'nb_underscore', 'nb_tilde', 'nb_percent', 'nb_slash', 'nb_star',
       'nb_colon', 'nb_comma', 'nb_semicolumn', 'nb_dollar', 'nb_space',
       'nb_www', 'nb_com', 'nb_dslash', 'http_in_path', 'https_token',
       'ratio_digits_url', 'ratio_digits_host', 'punycode', 'port',
       'tld_in_path', 'tld_in_subdomain', 'nb_subdomains',
       'abnormal_subdomain', 'prefix_suffix', 'path_extension',
       'length_words_raw', 'char_repeat', 'shortest_word_host',
       'shortest_word_path', 'longest_words_raw', 'longest_word_host',
       'longest_word_path', 'avg_words_raw', 'avg_word_host', 'avg_word_path'
    ]]
X_html_test = df_con[[
        'phish_hints', 'domain_in_brand', 'nb_hyperlinks', 'ratio_intHyperlinks',
        'ratio_extHyperlinks', 'ratio_extRedirection', 'ratio_extErrors',
        'external_favicon', 'links_in_tags', 'ratio_extMedia', 'safe_anchor',
        'empty_title', 'domain_in_title', 'domain_with_copyright',
        'has_meta_refresh', 'has_js_redirect'
        ]]
X_ai_test = df_con[['creates_urgency', 'uses_threats', 'requests_sensitive_info',
            'offers_unrealistic_rewards', 'has_spelling_grammar_errors',
            'impersonated_brand', 'has_valid_copyright_year',
            'is_content_login_focused', 'has_rich_navigation',
            'has_physical_address', 'has_phone_number',
            'content_consistency_score', 'language_professionalism_score',
            'overall_phishing_likelihood_score', 'text_length'
            ]]
y = df_con[['target']]

In [16]:
bool_col = ['creates_urgency', 'uses_threats', 'requests_sensitive_info',
            'offers_unrealistic_rewards', 'has_spelling_grammar_errors',
            'has_valid_copyright_year', 'is_content_login_focused',
            'has_rich_navigation', 'has_physical_address', 'has_phone_number']
X_ai_test[bool_col] = X_ai_test[bool_col].astype(int)
X_ai_test['impersonated_brand'] = [1 if k else 0 for k in X_ai_test['impersonated_brand'].notnull()]

/tmp/ipykernel_4752/1533107422.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_ai_test[bool_col] = X_ai_test[bool_col].astype(int)
/tmp/ipykernel_4752/1533107422.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_ai_test['impersonated_brand'] = [1 if k else 0 for k in X_ai_test['impersonated_brand'].notnull()]

In [17]:
X_ai_test

,creates_urgency,uses_threats,requests_sensitive_info,offers_unrealistic_rewards,has_spelling_grammar_errors,impersonated_brand,has_valid_copyright_year,is_content_login_focused,has_rich_navigation,has_physical_address,has_phone_number,content_consistency_score,language_professionalism_score,overall_phishing_likelihood_score,text_length
41613,0,0,0,0,0,0,1,0,1,1,1,10.0,10.0,2.0,5543
33558,0,0,0,0,0,0,0,0,0,0,0,7.0,10.0,2.0,2838
42697,0,0,0,0,0,0,1,0,1,0,0,8.0,9.0,2.0,5332
41343,0,0,0,0,0,1,1,0,1,0,0,8.0,9.0,2.0,8211
12741,0,0,1,0,0,0,1,1,1,0,0,8.0,10.0,6.0,3740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38594,0,0,0,0,0,0,1,0,1,1,1,10.0,10.0,0.0,8113
1010,0,0,0,0,0,0,1,0,1,0,1,8.0,9.0,2.0,10244
34569,0,0,0,0,0,0,0,0,1,0,0,7.0,9.0,2.0,4470
9500,0,0,1,0,0,0,1,0,1,0,0,7.0,9.0,3.0,4039
13543,0,0,0,0,0,1,1,0,1,1,1,9.0,10.0,2.0,5819

In [18]:
y_pred_proba_url = xgb_url_model.predict_proba(X_url_test)[:, 1]
y_pred_proba_html = xgb_html_model.predict_proba(X_html_test)[:, 1]
y_pred_proba_ai = xgb_ai_model.predict_proba(X_ai_test)[:, 1]

print('url', len(y_pred_proba_url))
print('html', len(y_pred_proba_html))
print('ai',len(y_pred_proba_ai))

url 43672
html 43672
ai 43672

In [19]:
print('url', y_pred_proba_url)
print('html', y_pred_proba_html)
print('ai',y_pred_proba_ai)

url [0.99886775 0.0031973  0.99501157 ... 0.99817586 0.9972435  0.99604166]
html [0.8467572  0.01824783 0.8482705  ... 0.04594157 0.8721617  0.6683604 ]
ai [0.8660285  0.2080265  0.7114483  ... 0.76841927 0.7524055  0.67354125]

In [20]:
import numpy as np

In [21]:
X_meta = np.c_[y_pred_proba_url, y_pred_proba_html, y_pred_proba_ai]
y_meta = y

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [23]:
len(y_meta[y_meta['target'] == 1])

38482

In [24]:
meta_model = LogisticRegression(class_weight='balanced')
meta_model.fit(X_meta, y_meta)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(class_weight='balanced')

In [ ]:
%%capture
!pip install joblib

In [27]:
import joblib
joblib.dump(meta_model, 'meta_logistic_final.pkl')

['meta_logistic_final.pkl']